// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB61UQO9nzFhpdQpsxHCGDedlmYm03Z5mE',
    appId: '1:858141317035:web:ca28e81e01aff9e4e824ee',
    messagingSenderId: '858141317035',
    projectId: 'nasa-space-apps-challeng-b676a',
    authDomain: 'nasa-space-apps-challeng-b676a.firebaseapp.com',
    storageBucket: 'nasa-space-apps-challeng-b676a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhBvarfJNjw0Qt6OdVHsL3xyOUDy7naFo',
    appId: '1:858141317035:android:adb41210838f3b15e824ee',
    messagingSenderId: '858141317035',
    projectId: 'nasa-space-apps-challeng-b676a',
    storageBucket: 'nasa-space-apps-challeng-b676a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPm48LgNKdUhgxqrzfFJE1F7GIK4_moFQ',
    appId: '1:858141317035:ios:3dbac40b17316fa4e824ee',
    messagingSenderId: '858141317035',
    projectId: 'nasa-space-apps-challeng-b676a',
    storageBucket: 'nasa-space-apps-challeng-b676a.appspot.com',
    iosClientId: '858141317035-cdq74th8f5juo8h4nddt2pp2ta77rq05.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapsInFlutter',
  );

}